### ISSUE TITLE
3d rendering

### ISSUE THREAD

**Issue by otiskujawa** [Geoxor/Shaii#134]
It's broken
New
![image](https://user-images.githubusercontent.com/49094075/163440492-93317f73-7da4-4e37-af54-2bf5330ac1be.png)
Old version
![image](https://user-images.githubusercontent.com/49094075/163440579-2654376b-6b71-4c5b-bca6-c769e4c9dbe2.png)

**Comment by Geoxor** [comment]
are you sure your machine has a gpu with drivers properly installed?

**Comment by N1kO23** [comment]
Can you provide the output of `xrandr` command?

**Comment by otiskujawa** [comment]
After installing drivers(during distro upgrade) everything works
Propably nuked drivers while compiling kernel
I wonder why on the same machine one bot worked and the other one didn't
