### ISSUE TITLE
Make it avoiding saying n-word and other stuff

### ISSUE THREAD

**Issue by qexat** [Geoxor/Shaii#60]
You should make it checking what Shaii is going to send to avoid accidentally sending the n-word :skull:

**Comment by Niekxd** [comment]
Probably a good idea to run the banned words checker over the match return

**Comment by qexat** [comment]
It could be fixed by creating a function that converts the `result` string to `IMessage` then putting the output through the [`moderation middleware`](https://github.com/Geoxor/Shaii/tree/main/src/middleware/moderationMiddleware.shaii.ts)

**Comment by N1kO23** [comment]
There could be a stripped down version of moderation middleware that filters the result strings and censors the blacklisted words/sentences
