### ISSUE TITLE
Putting commands in an embed on ~help

### ISSUE THREAD

**Issue by qexat** [Geoxor/Shaii#61]
The current display in a raw text file is not readable on mobile, and not user-friendly in general - so I suggest to put the commands in an embed

**Comment by Geoxor** [comment]
it is as a text file because they don't fit in an embed

**Comment by Geoxor** [comment]
2000 character limit

**Comment by qexat** [comment]
> it is as a text file because they don't fit in an embed

isn't it possible to make pagination with different categories?

**Comment by qexat** [comment]
Closing because this issue is already in #81
