### ISSUE TITLE
Transform command not working

### ISSUE THREAD

**Issue by Geoxor** [Geoxor/Shaii#70]
it seems to be dumping the buffer it gets back for some reason

**Comment by qexat** [comment]
Maybe the error caught isn't equal to `"TypeError: Cannot read property 'getUniformLocation' of null"`? Should be checked

**Comment by Geoxor** [comment]
well she does send an image so it doesn't error

**Comment by qexat** [comment]
Transform works, just not with 3D Commands since they aren't in `ImageProcessors` array.
