### ISSUE TITLE
Improving 'command not found'

### ISSUE THREAD

**Issue by qexat** [Geoxor/Shaii#72]
Shaii could check commands which have a name close to what the user typed and say something like: `Did you mean: {command_name}` in addition to the classic message

**Comment by Geoxor** [comment]
![image](https://user-images.githubusercontent.com/34042825/145447281-4e12cddb-5e49-4fd3-a8fa-e7c0fd79fb56.png)

**Comment by qexat** [comment]
should suggest another command only if the levenshtein distance is lower than 10

**Comment by qexat** [comment]
> should suggest another command only if the levenshtein distance is lower than 6

well actually this is a bit too much, let's say 3

**Comment by qexat** [comment]
thank you @Bluskript for the module suggestion
